substitutions:
  _CACHE: "true"
  _BUILD_CACHE_BUCKET: gs://wise-coyote-827/build-cache

steps:
- id: restore-m2-cache
  name: gcr.io/cloud-builders/gsutil
  waitFor: ['-']
  entrypoint: bash
  dir: /root
  args:
  - -c
  - |
    (
      mkdir -p .m2 && ${_CACHE} &&
      gsutil cp ${_BUILD_CACHE_BUCKET}/m2.tgz /tmp/m2.tgz &&
      tar xzf /tmp/m2.tgz
    ) || echo "no cache found"
  volumes:
  - name: user.home
    path: /root

- id: build
  name: gcr.io/cloud-builders/mvn
  waitFor: ['restore-m2-cache']
  args: ['package']
  volumes:
  - name: user.home
    path: /root

- id: update-m2-cache
  name: gcr.io/cloud-builders/gsutil
  waitFor: ['build']
  entrypoint: bash
  dir: /root
  args:
  - -c
  - |
    (
      ${_CACHE} &&
      tar czf /tmp/m2.tgz .m2 &&
      gsutil cp /tmp/m2.tgz ${_BUILD_CACHE_BUCKET}/m2.tgz
    ) || echo "unable to update cache"
  volumes:
  - name: user.home
    path: /root
